### ISSUE TITLE
Ask index panic

### ISSUE THREAD

**Issue by asutula** [textileio/filecoin#53]
Just saw this panic when running the server:
```
panic: runtime error: index out of range [0] with length 0

goroutine 53 [running]:
github.com/textileio/filecoin/index/ask.calculateMedian(0xc0003541e0, 0x0)
	/Users/aaron/code/textile/filecoin/index/ask/ask.go:263 +0x3d6
github.com/textileio/filecoin/index/ask.(*AskIndex).updateIndex(0xc000426000, 0x0, 0x0)
	/Users/aaron/code/textile/filecoin/index/ask/ask.go:224 +0x760
github.com/textileio/filecoin/index/ask.(*AskIndex).refreshAsks(0xc000426000, 0x0, 0x0)
	/Users/aaron/code/textile/filecoin/index/ask/ask.go:149 +0x79
github.com/textileio/filecoin/index/ask.(*AskIndex).runBackgroundAskCache(0xc000426000)
	/Users/aaron/code/textile/filecoin/index/ask/ask.go:131 +0x95
created by github.com/textileio/filecoin/index/ask.New
	/Users/aaron/code/textile/filecoin/index/ask/ask.go:87 +0x23d
```

**Comment by jsign** [comment]
Oh I see the problem. Will include it in the next PR.
